spring:
  profiles:
    active: local
    group:
      local: common
      live: common

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: make-order
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  access-secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  refresh-secret: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
  access-expiration: 600000  # 10 min: 10min * 60 sec * 1000 millisecond
  refresh-expiration: 10800000  # 10800000 3 hours: 3hours * 60min * 60sec * 1000 millisecond
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8802/MAKE_ORDER?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ENC(BO7K+uxnWF7VASHk8EnQBg==)
    password: ENC(gODsqBKdBceX3ye3XV6E+5ZZ7jNT2FSf)
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
---
spring:
  config:
    activate:
      on-profile: live
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(1yjYVr//BsK68vsGsOgtyMv63124qO1p0zESP9UDGY3e2Ko89q6yQRGT8gwLHnci1F/hSRAMyjyVtXXN/8GRE6dGl+SbX2H2mVScb9te+KDbZ22zxhYNxefQyfIXZLbPbvgzZJ40MaWayxefOfRPTF6z7qe39I01)
    username: ENC(0qljv+W84YOGe48XhVGLJg==)
    password: ENC(QqlGweuQKWMTOeocsSN1sxFAndkcohA/)
